[package]
name = "day_03"
version = "0.1.0"
authors = ["Niklas Long <niklas@long.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13"
ndarray-linalg = { version = "0.12", features = ["intel-mkl"] }
